
on:
push:
    branches:
      - dev
 
 # Job to build and publish the dacpac
              
              
   build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.3.0
      # Build dacpac using dotnet build
      - name: Build Database project
        run: |
          dotnet build
      # Publish artifact
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: SQLDB
          path: ${{ github.workspace }}/bin/Debug/
